In [13]:
import numpy as np

In [8]:
arr1 = np.arange(1, 11) 

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

shape1 = np.shape(arr1)

dtype1 = arr1.dtype

shape2 = np.shape(arr2)

dtype2 = arr2.dtype

dtype_float = np.float32

print(shape1)
print(dtype1)
print(shape2)
print(dtype2)
print(dtype_float.__name__)


(10,)
int64
(3, 3)
int64
float32


In [11]:
arr1 = np.arange(1, 11)

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

first_elem = arr1[0]

last_elem = arr1[-1]

middle_elem = arr1[len(arr1)//2]

slice_arr = arr1[2:5]

row2 = arr2[1, :]

col3 = arr2[:, 2]

print(first_elem)
print(last_elem)
print(middle_elem)
print(slice_arr)
print(row2)
print(col3)

1
10
6
[3 4 5]
[4 5 6]
[3 6 9]


In [ ]:
arr =  [[88, 35, 62],[11, 98, 34],[64, 24, 48]]

min = np.min(arr)
max = np.max(arr)
sum = np.sum(arr)
mean = np.mean(arr)
std = np.std(arr)

sumOfCol = np.sum(arr, axis=1)
meanOfCol = np.mean(arr, axis=0)

sumOfRow = np.sum(arr, axis=0)
meanOfRow = np.mean(arr, axis=1)

print(min)
print(max)
print(sum)
print(mean)
print(std)

print(sumOfRow)
print(meanOfRow)

print(sumOfCol)
print(meanOfCol)

11
98
464
51.55555555555556
27.38252123409754
[185 143 136]
[54.33333333 52.33333333 48.        ]
[163 157 144]
[61.66666667 47.66666667 45.33333333]


In [19]:
A = [[5, 6, 8],[7, 2, 4],[1, 6, 3]]

B =  [10, 20, 30]

C = np.add(A,B)

D = np.subtract(A,B)

print(C)
print(D)



[[15 26 38]
 [17 22 34]
 [11 26 33]]
[[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]


In [24]:
import time

randomArr = np.array([1,3,4,2,11,12,14,25,19,18])

randomArr1 = np.square(randomArr)

print(randomArr1)

randomArr2 = np.sqrt(randomArr)

print(randomArr2)


start = time.time()
newArr = np.array([[1,2],[3,4],[5,6]])
end = time.time()
print(np.square(newArr))
print(np.sqrt(newArr))

print("Thời gian chạy np.sqrt =", end - start, "giây")


[  1   9  16   4 121 144 196 625 361 324]
[1.         1.73205081 2.         1.41421356 3.31662479 3.46410162
 3.74165739 5.         4.35889894 4.24264069]
[[ 1  4]
 [ 9 16]
 [25 36]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
Thời gian chạy np.sqrt = 6.127357482910156e-05 giây


In [29]:
arr = [[3, 7, 4, 5],[3, 5, 2, 4],[6, 3, 9, 7],[4, 8, 3, 5]]

meanCol = np.mean(arr, axis=0)

print(meanCol)

meanRow = np.mean(arr, axis=1)

print(meanRow)




stdRow = np.std(arr, axis=1)

meanCol = np.mean(arr, axis=1)


stdCol = np.std(arr, axis=0)

meanRow = np.mean(arr, axis=0)

print(stdCol)

print(stdRow)

print(meanCol)

print(sumRow)






[4.   5.75 4.5  5.25]
[4.75 3.5  6.25 5.  ]
[1.22474487 1.92028644 2.6925824  1.08972474]
[1.47901995 1.11803399 2.16506351 1.87082869]
[4.75 3.5  6.25 5.  ]
[16 23 18 21]


In [39]:
arr = np.random.randint(20, size=(5,5))
start = time.time()
newArr =  [10, 20, 30, 40, 50]

add = arr + newArr
subtract = arr - newArr

square = np.square(arr)

addFive = arr + 5

end = time.time()

print(addFive)

print("Thời gian thủ công", end - start, "giây")


[[16 23 19 23 15]
 [19 22 12  8 11]
 [ 6 13 20 22 17]
 [14 21 23  9  9]
 [ 6 23  9  5  7]]
Thời gian thủ công 0.0004909038543701172 giây


In [46]:
arr = np.random.randint(30, size=(3,3,3))

reverse = np.linalg.inv(arr)

einvalues, einvectors = np.linalg.eig(arr)

print("Gia tri dao:\n", reverse)

print("\n")
print("\n")
print("\n")
print("\n")

print(einvalues)

print("\n")
print("\n")
print("\n")
print("\n")

print(einvectors)

Gia tri dao:
 [[[-0.02954491  0.05313319 -0.00262092]
  [ 0.04336431 -0.09411484  0.11675006]
  [ 0.01262807  0.06599952 -0.11984751]]

 [[ 0.12642629  0.0109539  -0.02236422]
  [-0.00775901  0.10041077 -0.03833866]
  [-0.00091283 -0.0470105   0.0543131 ]]

 [[-0.0248538   0.07602339 -0.0380117 ]
  [ 0.11842105 -0.13533835 -0.0037594 ]
  [-0.05701754  0.06516291  0.03884712]]]








[[ 52.84323015+0.j        -15.82406385+0.j         -5.0191663 +0.j       ]
 [ 35.31300796+0.j          7.84349602+0.7243586j   7.84349602-0.7243586j]
 [ -5.08165606+0.j         17.62608748+0.j         53.45556858+0.j       ]]








[[[-0.67883445+0.j         -0.75932562+0.j
    0.24839752+0.j        ]
  [-0.6372387 +0.j          0.50135296+0.j
   -0.7639284 +0.j        ]
  [-0.36484329+0.j          0.41481298+0.j
    0.59557709+0.j        ]]

 [[ 0.14444371+0.j          0.87581047+0.j
    0.87581047-0.j        ]
  [ 0.47668208+0.j         -0.04686459-0.40361908j
   -0.04686459+0.40361908j]
  [ 0.8671275