In [38]:
import numpy as np
import json
import pandas as pd

In [19]:
arr  = np.random.randint(1, 100, size = 10)

print(arr)

even_arr = arr[arr % 2 == 0]

print(even_arr)

tuple_data = tuple(arr.tolist())

print(tuple_data)

dict_data = {i: arr[i].tolist() for i in range(len(arr))}

print(dict_data)

count_duplicates = len(arr) - len(np.unique(arr))

print(count_duplicates)

[31 20 85 67 91 30 88 80 78 21]
[20 30 88 80 78]
(31, 20, 85, 67, 91, 30, 88, 80, 78, 21)
{0: 31, 1: 20, 2: 85, 3: 67, 4: 91, 5: 30, 6: 88, 7: 80, 8: 78, 9: 21}
0


In [26]:
with open("data.txt", "r") as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())


with open("student.json", "w") as file:
    file.write('{"name": "An","age": 20,"scores": [8, 9, 7]}')


with open("student.json", "r") as file:
    data = json.load(file)
    print(data)


101010101001010101001
1101000101011010101010
11010101000101010101010
10101001100011101011
10101010100011110101010
{'name': 'An', 'age': 20, 'scores': [8, 9, 7]}


In [36]:
arr = np.random.randint(0, 11, size = (4,3))
print(arr)

print(arr[1][2])

print(arr[:,2])

print(arr[2:, 1:])

[[ 7  1 10]
 [ 2  0 10]
 [ 8  9  3]
 [ 3  9  7]]
10
[10 10  3  7]
[[9 3]
 [9 7]]


In [48]:
name = ['An','Bình','Châu','Dũng','Hà']

age = [20,21,22,20,23]

score = [7.5, 8.0, 6.5, 9.0, 8.5] 

df = pd.DataFrame({'Name': name, 'Age': age, 'Score': score})
print(df.info())

print(df.describe())

print(df[df['Score'] >= 8.0])
newDf = df[df['Score'] >= 8.0]


listed_data = newDf.values.tolist()
print(listed_data)




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Age     5 non-null      int64  
 2   Score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes
None
            Age     Score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000
   Name  Age  Score
1  Bình   21    8.0
3  Dũng   20    9.0
4    Hà   23    8.5
[['Bình', 21, 8.0], ['Dũng', 20, 9.0], ['Hà', 23, 8.5]]


In [62]:

students = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["An", "Binh", "Chau"]
})

scores = pd.DataFrame({
    "id": [1, 1, 2, 3, 3, 3],
    "score": [8.5, 9.0, 7.5, 6.0, 7.0, 8.0]
})

merged = students.merge(scores, on="id")

report = merged.groupby(["id", "name"])["score"].agg(["min","max","mean"]).reset_index()

report.to_csv("report.csv", index=False)
print(report)


   id  name  min  max  mean
0   1    An  8.5  9.0  8.75
1   2  Binh  7.5  7.5  7.50
2   3  Chau  6.0  8.0  7.00


In [67]:
a = [[1],[2],[3],[4]]

b = [[10,20,30,40,50]]

mulArr = np.dot(a, b)
print(mulArr)

print(np.sqrt(mulArr))

print(np.log(mulArr))


print(np.mean(mulArr, axis=1))

[[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
[[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]
[[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]
[ 30.  60.  90. 120.]


In [91]:
import pandas as pd
import numpy as np

# Tạo dataset
data = {
    'name': ['An', 'Bình', 'Châu', 'Dũng'],
    'age': [20, np.nan, 22, 21],
    'score': [8.5, np.nan, 7.0, 9.0],
    'city': ['Hà Nội', 'HCM', np.nan, 'Hà Nội']
}

df = pd.DataFrame(data)

print("Dữ liệu thiếu:\n", df.isna())

df['age'] = df['age'].fillna(df['age'].mean())     
df['score'] = df['score'].fillna(df['score'].median())  
df['city'] = df['city'].fillna('Unknown')            
df['city'] = df['city'].astype('category')

def score_level(score):
    if score >= 8:
        return 'Good'
    elif score >= 7:
        return 'Average'
    else:
        return 'Bad'

df['score_level'] = df['score'].apply(score_level)

age_mean = df['age'].mean()
age_std = df['age'].std()
df['age_normalized'] = (df['age'] - age_mean) / age_std


age_cleaned = df['age'].tolist()
score_cleaned = df['score'].tolist()
city_category = df['city']
score_level_list = df['score_level'].tolist()
age_normalized = df['age_normalized'].tolist()

print("\nage_cleaned =", age_cleaned)
print("score_cleaned =", score_cleaned)
print("city (category) =", city_category)
print("score_level =", score_level_list)
print("age_normalized =", age_normalized)

Dữ liệu thiếu:
     name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False

age_cleaned = [20.0, 21.0, 22.0, 21.0]
score_cleaned = [8.5, 8.5, 7.0, 9.0]
city (category) = 0     Hà Nội
1        HCM
2    Unknown
3     Hà Nội
Name: city, dtype: category
Categories (3, object): ['HCM', 'Hà Nội', 'Unknown']
score_level = ['Good', 'Good', 'Average', 'Good']
age_normalized = [-1.224744871391589, 0.0, 1.224744871391589, 0.0]


In [92]:
import os
from pathlib import Path

os.makedirs('logs', exist_ok=True)

# Tạo file log mẫu
for date, user, action, duration in [
    ('2024-01-01', 'A', 'login', 5),
    ('2024-01-02', 'B', 'logout', 3)
]:
    with open(f'logs/log_{date}.json', 'w') as f:
        json.dump({"user": user, "action": action, "duration": duration}, f)

# Đọc và phân tích
data = []
for file in sorted(Path('logs').glob('log_*.json')):
    date = pd.to_datetime(file.stem.replace('log_', '')).date()
    with open(file) as f:
        log = json.load(f)
        log['date'] = date
        data.append(log)

df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])

# Tính tổng duration theo ngày
result = df.groupby(df['date'].dt.date)['duration'].sum().reset_index()
result.columns = ['Date', 'Total Duration']

# In kết quả
for _, row in result.iterrows():
    print(f"Date: {row['Date']}, Total Duration: {row['Total Duration']}")

# Xuất CSV
result.to_csv('daily_report.csv', index=False)
print("\n✓ Xuất ra: daily_report.csv")

Date: 2024-01-01, Total Duration: 5
Date: 2024-01-02, Total Duration: 3

✓ Xuất ra: daily_report.csv
